### PR TITLE
`<For />`  -  TS + Unit Test

### PR DESCRIPTION
**Pull request by SaburovBabur**
`<For />`

    - Added Typescript support
    - Unit Tested using Jest + React Testing Library

### CODE REVIEW

**Comment by SaburovBabur** [comment]
Will be adding Typescript and Unit testing for other utils very soon. 

Hope you like it, and will continue my journey as a contributor to this package!

---

Auto Completion Example

**Comment by DavidHDev** [comment]
Sorry Saburov, I want to keep the library written in JavaScript, with TypeScript support added in the special typings file so that it's compatible with TS projects. Somebody already handled that for the entire library so I will have to close your PR. Also, testing is nice to have but not required at the moment.

**Comment by SaburovBabur** [comment]
Will you accept pulls for tests in pure JS? All of the hooks and utils being with test coverage, I think will be a big plus. I will provide with coverage if will be accepted.

**Comment by DavidHDev** [comment]
Sure! If you want to contribute with JS tests you're welcome to do so.

**Pull request closed without merging**
