### PR TITLE
Create useTabNotification() hook

### PR DESCRIPTION
**Pull request by Yeine**
Description:
Develop a custom React Hook, useTabNotification(), that enables displaying notifications on the browser tab.

Acceptance Criteria:

- The useTabNotification() hook should provide functions or state variables to manage the tab notification state.
- It should allow showing and hiding notifications on the tab.

I believe it's what you wanted! Let me know if you want to change anything

### CODE REVIEW

**Comment by DavidHDev** [comment]
@Yeine hello, this looks good, but I'd also like to have the option to change the title of the tab (You have <x> new notifications), where <x> is also configurable, and optionally, to make it flash, meaning to have it switch between the original title and the "You have <x> new notifications" title like an animation.

**Comment by Yeine** [comment]
Very good Idea, I'll implement two strategy, prepend title or periodically switch between the given notification and the title. I'll do it today. This should cover most usecase

**Comment by Yeine** [comment]
I added "Flash message" feature that you can combine with prepend title or use only one of the two options. Don't hesitate if there's anything else you want to improve

**Comment by DavidHDev** [comment]
@Yeine could you please convert this to typescript? You can pull from the main branch, the library has been converted to TS

**Comment by Yeine** [comment]
Done! Once it'll be merged, I'll update the documentation website in another PR

**Review by DavidHDev — APPROVED** [review]
Awesome job, thanks!

**Pull request merged**
